version: "3.8"

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    image: backend
    container_name: my-spring-app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - backend-network
    restart: unless-stopped

  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: angular-frontend
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx-reverse-proxy
    volumes:
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${PWD}/nginx/log:/var/log/nginx
      - ${PWD}/nginx/certs:/etc/nginx/certs:ro
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    external: true
    driver: bridge
  frontend-network:
    external: true
    driver: bridge

