version: "3.8"

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: my-spring-app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend

  postgres:
    image: postgres:17
    container_name: my-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
  frontend-network:
