FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli && npm install

# Ajout explicite du proxy.conf.json
COPY proxy.conf.json ./ 

# Puis copie tout le reste du code
COPY . .

# Fix webpack + openssl issues
ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 4200

CMD ["npm", "start"]

