name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PROJECT_NAME: projet-workspace
  FRONTEND_IMAGE: angular-frontend
  BACKEND_IMAGE: spring-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./demo
          file: ./demo/Dockerfile.dev
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./angular-frontend
          file: ./angular-frontend/Dockerfile.dev
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest
